<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>yarn</string>
		<string>yarn.txt</string>
	</array>
	<key>firstLineMatch</key>
	<string>^#!.*\b(yarn)</string>
	<key>keyEquivalent</key>
	<string>^~Y</string>
	<key>name</key>
	<string>Yarn Dialogue</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#node-title</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#node-link</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#control-statement</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#interpolation</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#html</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>html</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>&lt;(\w+)&gt;</string>
					<key>name</key>
					<string>punctuation.definition.html.tag.yarn</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;\s*\/?(\w+)\s*\/?&gt;</string>
					<key>name</key>
					<string>punctuation.definition.html.tag.yarn</string>
				</dict>
			</array>
		</dict>
		<key>node-title</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>title:</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.nodeTitle.yarn</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>nodeTitle.yarn</string>
				</dict>
			</array>
		</dict>
		<key>node-link</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^\[\[</string>
					<key>name</key>
					<string>keyword.operator.nodeLinkStart.yarn</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\]\]$</string>
					<key>name</key>
					<string>keyword.operator.nodeLinkEnd.yarn</string>
				</dict>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolation</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>#</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.yarn</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.number-sign.yarn</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>"(.*?)"</string>
					<key>name</key>
					<string>punctuation.definition.string.yarn</string>
				</dict>
			</array>
		</dict>
		<key>function-call</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([a-z_A-Z0-9]+)(\(.*\))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.yarn</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.yarn</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#string</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#variable</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#keyword</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>end</key>
					<string>\s|\n|(?=&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.yarn</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>control-statement</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^&lt;&lt;</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.command.yarn</string>
						</dict>
					</dict>
					<key>end</key>
					<string>&gt;&gt;$</string>
					<key>name</key>
					<string>punctuation.definition.command.terminator.yarn</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#function-call</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variable</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keyword</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>interpolation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\$\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.yarn</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.yarn</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?:if|is|set|false|true|else|elseif|endif)</string>
					<key>name</key>
					<string>keyword.control.yarn</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\$)([a-zA-Z_][a-zA-Z0-9_])*</string>
					<key>name</key>
					<string>variable.other.normal.yarn</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.yarn</string>
	<key>uuid</key>
	<string>DDEEA3ED-6B1C-11D9-8B10-11AD93589AFF</string>
</dict>
</plist>
